### ISSUE TITLE
Flickering picture since the last update

### ISSUE THREAD

**Issue by Milongero71** [MiSTer-devel/AtariST_MiSTer#12]
Hello,
with the last update of the cores
Atari ST, GameBoy, Coco2 and ZX Spectrum I have now a flicker in the picture and OSD. I used a LCD monitor via the analog output on the I/O board. I have activated the scaler.
I have tested the previous versions and they give a clean picture.

**Comment by sorgelig** [comment]
Please don't spam. Your bug report has been noted already.

**Comment by Milongero71** [comment]
Sorry and thanx

Am Mi., 27. Jan. 2021 um 19:54 Uhr schrieb Alexey Melnikov <
notifications@github.com>:

**Comment by Rahkeesh2000** [comment]
I can verify this problem still exists. I would describe the "flickering" as vertical lines appear slightly wavey. Saw this on two different LCDs over VGA connection using VGA scaler around 1080p. Does not appear on the same monitors using DVI/HDMI, nor does it appear using non-scaled analog output w/framedoubler, nor can I see it on a VGA monitor. I also haven't seen this in any other current core including gameboy.

**Comment by Rahkeesh2000** [comment]
Feb 24 2021 update has completely fixed this issue for me. Image is rock steady over vga_scaler now.

**Comment by sorgelig** [comment]
it was known problem and waited for a bigger update.
