### ISSUE TITLE
Core doesn't load if default config's .img is renamed

### ISSUE THREAD

**Issue by Left-Empty** [MiSTer-devel/AtariST_MiSTer#3]
Hello, and what a wonderful core!

I ran into a slight issue that wasn't too much trouble to get around but I'll still submit it.

I had set a default configuration with a tos.img. I decided I wanted to have both a 50hz and 60hz TOS, so I renamed that initial img file. When then starting it, the core would just freeze right away, without any input available. The only option was to reboot the MiSTer.
Renaming one of the files back to TOS.img solved it of course.

Cheers!

**Comment by sorgelig** [comment]
Well, it seems affected only VGA output. 
No problem on HDMI. Actually it doesn't freeze. It's just core doesn't produce video, so analog video is off.
I will check if it possible to output some fail safe video without bios.

**Comment by Left-Empty** [comment]
Thank you for your reply. I will remember to include what video source I am using next time I am reporting something!
