### ISSUE TITLE
20200508 version doesn't seem able to load any disk

### ISSUE THREAD

**Issue by Left-Empty** [MiSTer-devel/AtariST_MiSTer#7]
Greetings,

I just tried the new version: it seems unable to recognize any floppy image anymore, be it dsk or tos images, or any hard drives.
Its inability to load the files is hinted by selecting a 50hz tos image: it doesn't even switch the refresh rate as it normally does.
Reverting to the previous version everything works fine.

I am using VGA out, with 128MB SDRam and 20200429 MiSTer.

Best regards,

**Comment by sorgelig** [comment]
For me it works fine.

**Comment by Left-Empty** [comment]
I redownloaded the file and now it works. Silly computers!
